/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package charmaker2.view;

/**
 *
 * @author richard
 */
public class CharMakerWindow extends javax.swing.JFrame {

    /**
     * Creates new form CharMakerWindow
     */
    public CharMakerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jFileChooser1 = new javax.swing.JFileChooser();
    dialogAddCharacter = new javax.swing.JDialog();
    jPanel3 = new javax.swing.JPanel();
    dialogLabelCharacter = new javax.swing.JLabel();
    dialogLabelCharacterChar = new javax.swing.JLabel();
    dialogTextFieldCharacterChar = new javax.swing.JTextField();
    dialogLabelCharacterInt = new javax.swing.JLabel();
    dialogSpinnerCharacterInt = new javax.swing.JSpinner();
    dialogLabelCharacterHex = new javax.swing.JLabel();
    dialogSpinnerCharacterHex = new javax.swing.JSpinner();
    jPanel7 = new javax.swing.JPanel();
    dialogLabelDescription = new javax.swing.JLabel();
    dialogTextFieldDescription = new javax.swing.JTextField();
    jPanel9 = new javax.swing.JPanel();
    dialogButtonOK = new javax.swing.JButton();
    dialogButtonCancel = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    panelInput = new javax.swing.JPanel();
    panelFileOperation = new javax.swing.JPanel();
    buttonOpen = new javax.swing.JButton();
    buttonNew = new javax.swing.JButton();
    buttonSave = new javax.swing.JButton();
    panelEditorInput = new javax.swing.JPanel();
    panelEditor = new javax.swing.JPanel();
    tabbedPaneFont = new javax.swing.JTabbedPane();
    panelEditorControl = new javax.swing.JPanel();
    labelColumns = new javax.swing.JLabel();
    spinnerColumns = new javax.swing.JSpinner();
    checkBoxColumns = new javax.swing.JCheckBox();
    labelRows = new javax.swing.JLabel();
    spinnerRows = new javax.swing.JSpinner();
    buttonSetGrid = new javax.swing.JButton();
    panelHeaderControl = new javax.swing.JPanel();
    labelDatatype = new javax.swing.JLabel();
    comboBoxDatatype = new javax.swing.JComboBox<>();
    labelFontName = new javax.swing.JLabel();
    textFieldFontName = new javax.swing.JTextField();
    radioButton0 = new javax.swing.JRadioButton();
    radioButton90 = new javax.swing.JRadioButton();
    radioButton180 = new javax.swing.JRadioButton();
    radioButton270 = new javax.swing.JRadioButton();
    checkBoxMirrorX = new javax.swing.JCheckBox();
    checkBoxMirrorY = new javax.swing.JCheckBox();
    panelCharacters = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    buttonAddChar = new javax.swing.JButton();
    buttonEditChar = new javax.swing.JButton();
    buttonRemoveChar = new javax.swing.JButton();
    buttonSortChars = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    buttonSetChar = new javax.swing.JButton();
    buttonShowPreview = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    listChars = new javax.swing.JList<>();
    panelPreview = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    textAreaPreviewInput = new javax.swing.JTextArea();
    jPanel8 = new javax.swing.JPanel();
    labelPreviewPixelSize = new javax.swing.JLabel();
    spinnerPreviewPixelSize = new javax.swing.JSpinner();
    buttonAddText = new javax.swing.JButton();
    buttonClearText = new javax.swing.JButton();
    panelPreviewFont = new javax.swing.JPanel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    menuItemNewCharacterSet = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    menuItemLoadCharacterSet = new javax.swing.JMenuItem();
    menuItemSaveCharacterSet = new javax.swing.JMenuItem();
    jSeparator2 = new javax.swing.JPopupMenu.Separator();
    menuItemQuit = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    menuItemLoadXML = new javax.swing.JMenuItem();
    jSeparator3 = new javax.swing.JPopupMenu.Separator();
    menuItemWriteHeader = new javax.swing.JMenuItem();

    dialogAddCharacter.setMinimumSize(new java.awt.Dimension(350, 150));
    dialogAddCharacter.getContentPane().setLayout(new javax.swing.BoxLayout(dialogAddCharacter.getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

    jPanel3.setLayout(new java.awt.GridBagLayout());

    dialogLabelCharacter.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
    jPanel3.add(dialogLabelCharacter, gridBagConstraints);

    dialogLabelCharacterChar.setText("jLabel2");
    jPanel3.add(dialogLabelCharacterChar, new java.awt.GridBagConstraints());

    dialogTextFieldCharacterChar.setText("jTextField1");
    dialogTextFieldCharacterChar.setMinimumSize(new java.awt.Dimension(22, 22));
    jPanel3.add(dialogTextFieldCharacterChar, new java.awt.GridBagConstraints());

    dialogLabelCharacterInt.setText("jLabel3");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    jPanel3.add(dialogLabelCharacterInt, gridBagConstraints);

    dialogSpinnerCharacterInt.setMinimumSize(new java.awt.Dimension(40, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    jPanel3.add(dialogSpinnerCharacterInt, gridBagConstraints);

    dialogLabelCharacterHex.setText("jLabel1");
    jPanel3.add(dialogLabelCharacterHex, new java.awt.GridBagConstraints());

    dialogSpinnerCharacterHex.setMinimumSize(new java.awt.Dimension(60, 22));
    jPanel3.add(dialogSpinnerCharacterHex, new java.awt.GridBagConstraints());

    dialogAddCharacter.getContentPane().add(jPanel3);

    jPanel7.setLayout(new java.awt.GridBagLayout());

    dialogLabelDescription.setText("jLabel4");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    jPanel7.add(dialogLabelDescription, gridBagConstraints);

    dialogTextFieldDescription.setText("jTextField2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel7.add(dialogTextFieldDescription, gridBagConstraints);

    dialogAddCharacter.getContentPane().add(jPanel7);

    dialogButtonOK.setText("jButton1");
    jPanel9.add(dialogButtonOK);

    dialogButtonCancel.setText("jButton2");
    jPanel9.add(dialogButtonCancel);

    dialogAddCharacter.getContentPane().add(jPanel9);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

    panelInput.setLayout(new java.awt.BorderLayout());

    buttonOpen.setText("jButton1");
    panelFileOperation.add(buttonOpen);

    buttonNew.setText("jButton2");
    panelFileOperation.add(buttonNew);

    buttonSave.setText("jButton3");
    panelFileOperation.add(buttonSave);

    panelInput.add(panelFileOperation, java.awt.BorderLayout.PAGE_END);

    panelEditorInput.setLayout(new java.awt.GridLayout(1, 0));

    panelEditor.setLayout(new java.awt.GridLayout(1, 0));
    panelEditorInput.add(panelEditor);

    panelEditorControl.setLayout(new java.awt.GridBagLayout());

    labelColumns.setText("jLabel4");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelEditorControl.add(labelColumns, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelEditorControl.add(spinnerColumns, gridBagConstraints);

    checkBoxColumns.setText("jCheckBox3");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelEditorControl.add(checkBoxColumns, gridBagConstraints);

    labelRows.setText("jLabel5");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelEditorControl.add(labelRows, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelEditorControl.add(spinnerRows, gridBagConstraints);

    buttonSetGrid.setText("jButton8");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelEditorControl.add(buttonSetGrid, gridBagConstraints);

    tabbedPaneFont.addTab("tab1", panelEditorControl);

    panelHeaderControl.setLayout(new java.awt.GridBagLayout());

    labelDatatype.setText("jLabel2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(labelDatatype, gridBagConstraints);

    comboBoxDatatype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(comboBoxDatatype, gridBagConstraints);

    labelFontName.setText("jLabel3");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(labelFontName, gridBagConstraints);

    textFieldFontName.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(textFieldFontName, gridBagConstraints);

    radioButton0.setText("jRadioButton1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(radioButton0, gridBagConstraints);

    radioButton90.setText("jRadioButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(radioButton90, gridBagConstraints);

    radioButton180.setText("jRadioButton3");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(radioButton180, gridBagConstraints);

    radioButton270.setText("jRadioButton4");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(radioButton270, gridBagConstraints);

    checkBoxMirrorX.setText("jCheckBox1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(checkBoxMirrorX, gridBagConstraints);

    checkBoxMirrorY.setText("jCheckBox2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    panelHeaderControl.add(checkBoxMirrorY, gridBagConstraints);

    tabbedPaneFont.addTab("tab2", panelHeaderControl);

    panelCharacters.setLayout(new java.awt.BorderLayout());

    jPanel2.setLayout(new java.awt.GridBagLayout());

    buttonAddChar.setText("jButton3");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
    jPanel2.add(buttonAddChar, gridBagConstraints);

    buttonEditChar.setText("jButton1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
    jPanel2.add(buttonEditChar, gridBagConstraints);

    buttonRemoveChar.setText("jButton4");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
    jPanel2.add(buttonRemoveChar, gridBagConstraints);

    buttonSortChars.setText("jButton5");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
    jPanel2.add(buttonSortChars, gridBagConstraints);

    panelCharacters.add(jPanel2, java.awt.BorderLayout.LINE_END);

    buttonSetChar.setText("jButton6");
    jPanel5.add(buttonSetChar);

    buttonShowPreview.setText("jButton7");
    jPanel5.add(buttonShowPreview);

    panelCharacters.add(jPanel5, java.awt.BorderLayout.PAGE_END);

    jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

    listChars.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane2.setViewportView(listChars);

    jPanel6.add(jScrollPane2);

    panelCharacters.add(jPanel6, java.awt.BorderLayout.CENTER);

    tabbedPaneFont.addTab("tab3", panelCharacters);

    panelEditorInput.add(tabbedPaneFont);

    panelInput.add(panelEditorInput, java.awt.BorderLayout.CENTER);

    jPanel1.add(panelInput);

    panelPreview.setLayout(new java.awt.BorderLayout());

    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

    textAreaPreviewInput.setColumns(20);
    textAreaPreviewInput.setRows(5);
    jScrollPane1.setViewportView(textAreaPreviewInput);

    jPanel4.add(jScrollPane1);

    jPanel8.setLayout(new java.awt.GridLayout(1, 0));

    labelPreviewPixelSize.setText("jLabel1");
    jPanel8.add(labelPreviewPixelSize);
    jPanel8.add(spinnerPreviewPixelSize);

    jPanel4.add(jPanel8);

    buttonAddText.setText("jButton1");
    jPanel4.add(buttonAddText);

    buttonClearText.setText("jButton2");
    jPanel4.add(buttonClearText);

    panelPreview.add(jPanel4, java.awt.BorderLayout.LINE_END);

    javax.swing.GroupLayout panelPreviewFontLayout = new javax.swing.GroupLayout(panelPreviewFont);
    panelPreviewFont.setLayout(panelPreviewFontLayout);
    panelPreviewFontLayout.setHorizontalGroup(
      panelPreviewFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 434, Short.MAX_VALUE)
    );
    panelPreviewFontLayout.setVerticalGroup(
      panelPreviewFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 178, Short.MAX_VALUE)
    );

    panelPreview.add(panelPreviewFont, java.awt.BorderLayout.CENTER);

    jPanel1.add(panelPreview);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jMenu1.setText("File");

    menuItemNewCharacterSet.setText("jMenuItem1");
    jMenu1.add(menuItemNewCharacterSet);
    jMenu1.add(jSeparator1);

    menuItemLoadCharacterSet.setText("jMenuItem2");
    jMenu1.add(menuItemLoadCharacterSet);

    menuItemSaveCharacterSet.setText("jMenuItem3");
    jMenu1.add(menuItemSaveCharacterSet);
    jMenu1.add(jSeparator2);

    menuItemQuit.setText("jMenuItem4");
    jMenu1.add(menuItemQuit);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");

    menuItemLoadXML.setText("jMenuItem1");
    jMenu2.add(menuItemLoadXML);
    jMenu2.add(jSeparator3);

    menuItemWriteHeader.setText("jMenuItem2");
    jMenu2.add(menuItemWriteHeader);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharMakerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharMakerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharMakerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharMakerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharMakerWindow().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonAddChar;
  private javax.swing.JButton buttonAddText;
  private javax.swing.JButton buttonClearText;
  private javax.swing.JButton buttonEditChar;
  private javax.swing.JButton buttonNew;
  private javax.swing.JButton buttonOpen;
  private javax.swing.JButton buttonRemoveChar;
  private javax.swing.JButton buttonSave;
  private javax.swing.JButton buttonSetChar;
  private javax.swing.JButton buttonSetGrid;
  private javax.swing.JButton buttonShowPreview;
  private javax.swing.JButton buttonSortChars;
  private javax.swing.JCheckBox checkBoxColumns;
  private javax.swing.JCheckBox checkBoxMirrorX;
  private javax.swing.JCheckBox checkBoxMirrorY;
  private javax.swing.JComboBox<String> comboBoxDatatype;
  private javax.swing.JDialog dialogAddCharacter;
  private javax.swing.JButton dialogButtonCancel;
  private javax.swing.JButton dialogButtonOK;
  private javax.swing.JLabel dialogLabelCharacter;
  private javax.swing.JLabel dialogLabelCharacterChar;
  private javax.swing.JLabel dialogLabelCharacterHex;
  private javax.swing.JLabel dialogLabelCharacterInt;
  private javax.swing.JLabel dialogLabelDescription;
  private javax.swing.JSpinner dialogSpinnerCharacterHex;
  private javax.swing.JSpinner dialogSpinnerCharacterInt;
  private javax.swing.JTextField dialogTextFieldCharacterChar;
  private javax.swing.JTextField dialogTextFieldDescription;
  private javax.swing.JFileChooser jFileChooser1;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JPopupMenu.Separator jSeparator2;
  private javax.swing.JPopupMenu.Separator jSeparator3;
  private javax.swing.JLabel labelColumns;
  private javax.swing.JLabel labelDatatype;
  private javax.swing.JLabel labelFontName;
  private javax.swing.JLabel labelPreviewPixelSize;
  private javax.swing.JLabel labelRows;
  private javax.swing.JList<String> listChars;
  private javax.swing.JMenuItem menuItemLoadCharacterSet;
  private javax.swing.JMenuItem menuItemLoadXML;
  private javax.swing.JMenuItem menuItemNewCharacterSet;
  private javax.swing.JMenuItem menuItemQuit;
  private javax.swing.JMenuItem menuItemSaveCharacterSet;
  private javax.swing.JMenuItem menuItemWriteHeader;
  private javax.swing.JPanel panelCharacters;
  private javax.swing.JPanel panelEditor;
  private javax.swing.JPanel panelEditorControl;
  private javax.swing.JPanel panelEditorInput;
  private javax.swing.JPanel panelFileOperation;
  private javax.swing.JPanel panelHeaderControl;
  private javax.swing.JPanel panelInput;
  private javax.swing.JPanel panelPreview;
  private javax.swing.JPanel panelPreviewFont;
  private javax.swing.JRadioButton radioButton0;
  private javax.swing.JRadioButton radioButton180;
  private javax.swing.JRadioButton radioButton270;
  private javax.swing.JRadioButton radioButton90;
  private javax.swing.JSpinner spinnerColumns;
  private javax.swing.JSpinner spinnerPreviewPixelSize;
  private javax.swing.JSpinner spinnerRows;
  private javax.swing.JTabbedPane tabbedPaneFont;
  private javax.swing.JTextArea textAreaPreviewInput;
  private javax.swing.JTextField textFieldFontName;
  // End of variables declaration//GEN-END:variables

    /**
     * @return the buttonAddChar
     */
    public javax.swing.JButton getButtonAddChar() {
        return buttonAddChar;
    }

    /**
     * @return the buttonAddText
     */
    public javax.swing.JButton getButtonAddText() {
        return buttonAddText;
    }

    /**
     * @return the buttonClearText
     */
    public javax.swing.JButton getButtonClearText() {
        return buttonClearText;
    }

    /**
     * @return the buttonNew
     */
    public javax.swing.JButton getButtonNew() {
        return buttonNew;
    }

    /**
     * @return the buttonOpen
     */
    public javax.swing.JButton getButtonOpen() {
        return buttonOpen;
    }

    /**
     * @return the buttonRemoveChar
     */
    public javax.swing.JButton getButtonRemoveChar() {
        return buttonRemoveChar;
    }

    /**
     * @return the buttonSave
     */
    public javax.swing.JButton getButtonSave() {
        return buttonSave;
    }

    /**
     * @return the buttonSetChar
     */
    public javax.swing.JButton getButtonSetChar() {
        return buttonSetChar;
    }

    /**
     * @return the buttonSetGrid
     */
    public javax.swing.JButton getButtonSetGrid() {
        return buttonSetGrid;
    }

    /**
     * @return the buttonShowPreview
     */
    public javax.swing.JButton getButtonShowPreview() {
        return buttonShowPreview;
    }

    /**
     * @return the buttonSortChars
     */
    public javax.swing.JButton getButtonSortChars() {
        return buttonSortChars;
    }

    /**
     * @return the checkBoxColumns
     */
    public javax.swing.JCheckBox getCheckBoxColumns() {
        return checkBoxColumns;
    }

    /**
     * @return the checkBoxMirrorX
     */
    public javax.swing.JCheckBox getCheckBoxMirrorX() {
        return checkBoxMirrorX;
    }

    /**
     * @return the checkBoxMirrorY
     */
    public javax.swing.JCheckBox getCheckBoxMirrorY() {
        return checkBoxMirrorY;
    }

    /**
     * @return the comboBoxDatatype
     */
    public javax.swing.JComboBox<String> getComboBoxDatatype() {
        return comboBoxDatatype;
    }

    /**
     * @return the labelColumns
     */
    public javax.swing.JLabel getLabelColumns() {
        return labelColumns;
    }

    /**
     * @return the labelDatatype
     */
    public javax.swing.JLabel getLabelDatatype() {
        return labelDatatype;
    }

    /**
     * @return the labelFontName
     */
    public javax.swing.JLabel getLabelFontName() {
        return labelFontName;
    }

    /**
     * @return the labelPreviewPixelSize
     */
    public javax.swing.JLabel getLabelPreviewPixelSize() {
        return labelPreviewPixelSize;
    }

    /**
     * @return the labelRows
     */
    public javax.swing.JLabel getLabelRows() {
        return labelRows;
    }

    /**
     * @return the listChars
     */
    public javax.swing.JList<String> getListChars() {
        return listChars;
    }

    /**
     * @return the panelEditor
     */
    public javax.swing.JPanel getPanelEditor() {
        return panelEditor;
    }

    /**
     * @return the radioButton0
     */
    public javax.swing.JRadioButton getRadioButton0() {
        return radioButton0;
    }

    /**
     * @return the radioButton180
     */
    public javax.swing.JRadioButton getRadioButton180() {
        return radioButton180;
    }

    /**
     * @return the radioButton270
     */
    public javax.swing.JRadioButton getRadioButton270() {
        return radioButton270;
    }

    /**
     * @return the radioButton90
     */
    public javax.swing.JRadioButton getRadioButton90() {
        return radioButton90;
    }

    /**
     * @return the spinnerColumns
     */
    public javax.swing.JSpinner getSpinnerColumns() {
        return spinnerColumns;
    }

    /**
     * @return the spinnerPreviewPixelSize
     */
    public javax.swing.JSpinner getSpinnerPreviewPixelSize() {
        return spinnerPreviewPixelSize;
    }

    /**
     * @return the spinnerRows
     */
    public javax.swing.JSpinner getSpinnerRows() {
        return spinnerRows;
    }

    /**
     * @return the textAreaPreviewInput
     */
    public javax.swing.JTextArea getTextAreaPreviewInput() {
        return textAreaPreviewInput;
    }

    /**
     * @return the textFieldFontName
     */
    public javax.swing.JTextField getTextFieldFontName() {
        return textFieldFontName;
    }

  /**
   * @return the jFileChooser1
   */
  public javax.swing.JFileChooser getjFileChooser1() {
    return jFileChooser1;
  }

  /**
   * @return the panelPreviewFont
   */
  public javax.swing.JPanel getPanelPreviewFont() {
    return panelPreviewFont;
  }

  /**
   * @return the dialogButtonCancel
   */
  public javax.swing.JButton getDialogButtonCancel() {
    return dialogButtonCancel;
  }

  /**
   * @return the dialogButtonOK
   */
  public javax.swing.JButton getDialogButtonOK() {
    return dialogButtonOK;
  }

  /**
   * @return the dialogLabelCharacter
   */
  public javax.swing.JLabel getDialogLabelCharacter() {
    return dialogLabelCharacter;
  }

  /**
   * @return the dialogLabelCharacterChar
   */
  public javax.swing.JLabel getDialogLabelCharacterChar() {
    return dialogLabelCharacterChar;
  }

  /**
   * @return the dialogLabelCharacterHex
   */
  public javax.swing.JLabel getDialogLabelCharacterHex() {
    return dialogLabelCharacterHex;
  }

  /**
   * @return the dialogLabelCharacterInt
   */
  public javax.swing.JLabel getDialogLabelCharacterInt() {
    return dialogLabelCharacterInt;
  }

  /**
   * @return the dialogLabelDescription
   */
  public javax.swing.JLabel getDialogLabelDescription() {
    return dialogLabelDescription;
  }

  /**
   * @return the dialogSpinnerCharacterInt
   */
  public javax.swing.JSpinner getDialogSpinnerCharacterInt() {
    return dialogSpinnerCharacterInt;
  }

  /**
   * @return the dialogTextFieldCharacterChar
   */
  public javax.swing.JTextField getDialogTextFieldCharacterChar() {
    return dialogTextFieldCharacterChar;
  }

  /**
   * @return the dialogTextFieldDescription
   */
  public javax.swing.JTextField getDialogTextFieldDescription() {
    return dialogTextFieldDescription;
  }

  /**
   * @return the dialogSpinnerCharacterHex
   */
  public javax.swing.JSpinner getDialogSpinnerCharacterHex() {
    return dialogSpinnerCharacterHex;
  }

  /**
   * @return the dialogAddCharacter
   */
  public javax.swing.JDialog getDialogAddCharacter() {
    return dialogAddCharacter;
  }

  /**
   * @return the tabbedPaneFont
   */
  public javax.swing.JTabbedPane getTabbedPaneFont() {
    return tabbedPaneFont;
  }

  /**
   * @return the menuItemLoadCharacterSet
   */
  public javax.swing.JMenuItem getMenuItemLoadCharacterSet() {
    return menuItemLoadCharacterSet;
  }

  /**
   * @return the menuItemLoadXML
   */
  public javax.swing.JMenuItem getMenuItemLoadXML() {
    return menuItemLoadXML;
  }

  /**
   * @return the menuItemNewCharacterSet
   */
  public javax.swing.JMenuItem getMenuItemNewCharacterSet() {
    return menuItemNewCharacterSet;
  }

  /**
   * @return the menuItemQuit
   */
  public javax.swing.JMenuItem getMenuItemQuit() {
    return menuItemQuit;
  }

  /**
   * @return the menuItemSaveCharacterSet
   */
  public javax.swing.JMenuItem getMenuItemSaveCharacterSet() {
    return menuItemSaveCharacterSet;
  }

  /**
   * @return the menuItemWriteHeader
   */
  public javax.swing.JMenuItem getMenuItemWriteHeader() {
    return menuItemWriteHeader;
  }

  /**
   * @return the buttonEditChar
   */
  public javax.swing.JButton getButtonEditChar() {
    return buttonEditChar;
  }
}
